title: Prof. Shailen Mishra's Courses
description: Course materials and other instructional details are found here.
theme: just-the-docs

url: https://shailenmishra.com/teaching-docs

aux_links:
  SWAT Moodle: https://moodle.swarthmore.edu/
